[package]
name = "pe-parser"
version = "2.1.1"
edition = "2021"
authors = ["Pavel Grigorenko <grigorenkopv@ya.ru>"]
description = "A small .EXE & .DLL parser"

[dependencies]
anyhow = "1.0"
clap = { version = "3.1", features = ["derive"] }
