name: PE
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  grade:
    runs-on: [self-hosted, os]
    timeout-minutes: 10
    name: 'Required tests'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install rust'
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
      - name: 'Run tests'
        run: source $HOME/.cargo/env && make validation-pe-tests import-dll-tests import-function-tests
  grade-export:
    runs-on: [self-hosted, os]
    timeout-minutes: 10
    name: 'Bonus: export'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Install rust'
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal
      - name: 'Run tests'
        run: source $HOME/.cargo/env && make export-function-tests
